name: test_atp
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  bluesky: ^0.18.0
  toml: ^0.16.0
  timeago: ^3.7.0
  cached_network_image: ^3.4.0
  logging: ^1.3.0
  video_player: ^2.9.2
  shared_preferences: ^2.3.3
  shimmer: ^3.0.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/creds.toml
